//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeignKeyInEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int EId { get; set; }
        public string EFName { get; set; }
        public string ELName { get; set; }
        public string EDesig { get; set; }
        public Nullable<int> DeptID { get; set; }
    
        public virtual Dept Dept { get; set; }
    }
}
