//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIExcercise2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPLPlayer
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public string PType { get; set; }
        public Nullable<double> PStrikeRate { get; set; }
        public string PTeam { get; set; }
    }
}
