//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWithDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int SId { get; set; }
        public Nullable<double> SFee { get; set; }
        public int SMonth { get; set; }
        public int SYear { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
